### ISSUE TITLE
Como PO_p, quiero iniciar el Product Backlog realizando un User Story Mapping

### ISSUE THREAD

**Issue by victorperezpiqueras** [victorperezpiqueras/TFG#1]

**Comment by paberlo** [comment]
Como ves las estimaciones se hacen por Issues; o sea, en nuestro caso por historia de usuario.
Las tareas que tú piensen que te hacen falta para llevarlo a cabo, puedes ponerlas en la descripción de la historia (En Add a description +).

**Comment by paberlo** [comment]
Hola, la has puesto como DevDone, pero solo cumples que has hecho el USMapping, pero no has añadido aún las historias al PB, y eso te llevará su tiempo :)
