### ISSUE TITLE
Como PO quiero que existan 3 tipos de usuarios para poder gestionar los distintos permisos

### ISSUE THREAD

**Issue by victorperezpiqueras** [victorperezpiqueras/TFG#15]
Los tipos de usuario serán:
- Product Owner
- Developer
- Stakeholder

**Comment by paberlo** [comment]
Todas estas features tienen "Como PO_p". Para el producto no es aconsejable usar "Como PO" ya que de lo que se trata es ver por qué le da valor al cliente o usuario, no al PO.

En este caso, cuando dije "Como PO" me refiero al futuro PO que use la aplicación; o sea, al usuario. Así que cambia los PO_p a PO, usuario PO, ... algo así.
