### ISSUE TITLE
Como PO quiero ver y editar DoD para poder revisarlas y actualizarlas a voluntad

### ISSUE THREAD

**Issue by victorperezpiqueras** [victorperezpiqueras/TFG#28]
Criterios de aceptación:
- El sistema pregunta si se quiere añadir al historial de DoDs la DoD modificada antes de borrarla.

**Comment by paberlo** [comment]
No creo que haga falta ver el historial de DoD. Es algo que evoluciona para representar qué se exige de los incrementos en general.

La utiliza el Scrum Team, pero la define el equipo de desarrollo, o la extiende a partir de una definición oficial de la empresa. Pero no es propiedad ni responsabilidad del PO, así que quizás no tenga mucho sentido que esté. Se podría poner como botón y acceder a ella si la interfaz no está muy cargada.

Los criterios de aceptación de los item sí tienen sentido que estén accesibles por el PO, ya que algún criterio puede ser definido por el PO además de los desarrolladores.
