### ISSUE TITLE
Como Tribunal, quiero que se escriba en la memoria el capítulo del Estado del Arte para que la memoria introduzca y aporte un contexto al trabajo realizado

### ISSUE THREAD

**Issue by victorperezpiqueras** [victorperezpiqueras/TFG#5]
En este capítulo se escribirán los siguientes apartados:
 -Poner Scrum en contexto y las funciones del Product Owner.
 -Comentar distintas herramientas de gestión de Scrum.
 -Hablar sobre las estimaciones que realiza el Product Owner.

**Comment by paberlo** [comment]
la mayoría sería un resumen del capítulo 8 de the Professional Product Owner. Con más énfasis en los distintos reports que se pueden hacer para ayudar a que el PO explique cómo va el proyecto.

**Comment by paberlo** [comment]
En el resumen de aplicaciones, distingue entre servicios online y Apps
